language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
sudo: false
jdk:
- openjdk11
branches:
  only:
  - java11
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script: mvn clean install -U -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

deploy:
  on:
    branch: java11
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
