
package org.cytoscape.work;

/**
 * This interface should be implemented by a TaskFactory.  It
 * allows a TaskFactory to state whether or not the current
 * environment is sufficient for Tasks generated by the factory to 
 * produce a meaningful result.  For example, a task generating a new network from a
 * selection of nodes needs a network with at least one node selected
 * to produce a meaningful result. 
 * <br/>
 * This interface will be used to determine
 * whether menu items and buttons generated from the TaskFactory should be
 * enabled.
 *
 * @CyAPI.Spi.Interface
 */
public interface TaskFactoryPredicate {

	/**
	 * Returns true if conditions are such that Tasks generated by the
	 * factory can be used in a meaningful way and retuns false otherwise.
	 * @return true if conditions are such that Tasks generated by the
	 * factory can be used in a meaningful way and retuns false otherwise.
	 */
	boolean isReady();	
}
