package org.cytoscape.view.presentation.property.table;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.geom.Rectangle2D;
import java.util.Map;

import org.cytoscape.model.CyColumn;
import org.cytoscape.model.CyRow;
import org.cytoscape.view.presentation.property.values.VisualPropertyValue;

public interface CellCustomGraphics extends VisualPropertyValue {
	
	/**
	 * Immutable session-unique identifier of this custom graphic generated by the 
	 * custom graphics manager.  If this returns null, the custom graphics manager 
	 * will generate a new identifier when this custom graphics is added.
	 * 
	 * @return Immutable ID as Long.
	 */
	Long getIdentifier();
		
	/**
	 * Set the session-unique identifier of this custom graphics.  This method is used by
	 * the renderer to track custom graphics objects for serialization/deserialization.  Your
	 * implementation should not generate or set this value.
	 * 
	 * @param id Immutable ID as Long.
	 */
	void setIdentifier(Long id);
	
	/**
	 * Set human readable display name.
	 * 
	 * @param displayName
	 */
	void setDisplayName(String displayName);
	
	/**
	 * Provides an optional map of key/value properties which define the custom graphics instance.
	 * @return A map of key/value properties.
	 */
	Map<String, Object> getProperties();
	
	/**
	 * Renders a scaled rasterized {@link Image} object.
	 * Usually, the image returned by this method is used as icons in GUI components.
	 * 
	 * @return rendered image object.
	 */
	Image getRenderedImage();
	
	void draw(Graphics g, Rectangle2D bounds, CyColumn column, CyRow row);

}
