package org.cytoscape.io.write;

import org.cytoscape.model.CyNetwork;
import org.cytoscape.view.model.CyNetworkView;

/**
 * A specialization of {@link CyWriterFactory} that allows a 
 * {@link CyNetworkView} to be specified and written.
 * @CyAPI.Spi.Interface
 */
public interface CyNetworkViewWriterFactory extends CyWriterFactory {

	/**
	 * Specifies the {@link CyNetwork} to be written by the 
	 * {@link CyWriter} Task generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param view The {@link CyNetworkView} to be written.
	 */
	void setNetwork(CyNetwork network);
	
	/**
	 * Specifies the {@link CyNetworkView} to be written by the 
	 * {@link CyWriter} Task generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param view The {@link CyNetworkView} to be written.
	 */
	void setNetworkView(CyNetworkView view);
}
