package org.cytoscape.io.write;


/**
 * A specialization of {@link CyWriterFactory} that allows a property Object to
 * be specified and written. See {@link org.cytoscape.property.CyProperty} for details on the type of Object.
 * @CyAPI.Spi.Interface
 */
public interface CyPropertyWriterFactory extends CyWriterFactory {

	/**
	 * Specifies the property object to be written by the {@link CyWriter} Task
	 * generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param property The property object to be written. In general 
	 * this object should be of types described in {@link org.cytoscape.property.CyProperty}.
	 */
	void setProperty(Object property);
}
