package org.cytoscape.io.write;


import org.cytoscape.session.CySession;

/**
 * A specialization of {@link CyWriterFactory} that allows a {@link org.cytoscape.session.CySession} to
 * be specified and written.
 * @CyAPI.Spi.Interface
 */
public interface CySessionWriterFactory extends CyWriterFactory {

	/**
	 * Specifies the {@link org.cytoscape.session.CySession} to be written by the {@link CyWriter} Task
	 * generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param session The {@link org.cytoscape.session.CySession} to be written.
	 */
	void setSession(CySession session);
}
