package org.cytoscape.io.write;

import org.cytoscape.model.CyTable;

/**
 * A specialization of {@link CyWriterFactory} that allows a {@link org.cytoscape.model.CyTable} to
 * be specified and written.
 */
public interface CyTableWriterFactory extends CyWriterFactory {

	/**
	 * Specifies the {@link org.cytoscape.model.CyTable} to be written by the {@link CyWriter} Task
	 * generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param table The {@link org.cytoscape.model.CyTable} to be written.
	 */
	void setTable(CyTable table);
}
