package org.cytoscape.io.write;


import org.cytoscape.view.presentation.RenderingEngine;

/**
 * A specialization of {@link CyWriterFactory} that allows a View 
 * rendered by the specified {@link RenderingEngine} to
 * be specified and written.
 * @CyAPI.Spi.Interface
 */
public interface PresentationWriterFactory extends CyWriterFactory {

	/**
	 * Specifies the {@link RenderingEngine} (which contains a View) 
	 * to be written by the {@link CyWriter} Task
	 * generated by this factory.  This method must be called 
	 * prior to calling the getWriter() method.
	 * @param re The {@link RenderingEngine} used to generate the image of the
	 * View it contains.
	 */
	void setRenderingEngine(final RenderingEngine<?> re);
}
